name: larch
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cmake=3.19.6
  - make
  - cxx-compiler
  - openmpi
  - openmpi-mpicc
  - openmpi-mpicxx
  - boost-cpp=1.76
  - automake
  - autoconf
  - libtool
  - yasm
  - ucx
  - zlib
  - git-lfs
