name: larch-dev
channels:
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  # larch: build time
  - python
  - gcc >=12.4.0,<14.0.0
  - gxx >=12.4.0,<14.0.0
  - cmake>=3.19.6
  - make
  - openmpi-mpicc >=4.1.0,<5.0
  - openmpi-mpicxx >=4.1.0,<5.0
  - automake
  - autoconf
  - libtool
  - yasm
  - openssh
  - libprotobuf
  - protobuf
  # larch: run time
  - openmpi >=4.1.0,<5.0
  - boost-cpp >=1.82
  - ucx >=1.16.0
  - zlib >=1.2
  - libhwloc
  # netam
  - pytorch-cpu
  # development
  - git
  - git-lfs
